In [1]:
import numpy as np
import time

np.random.seed(42)
print("Numpy version:",np.__version__)

Numpy version: 1.24.3


In [9]:
import time
import numpy as np

prices = list(range(1, 1_000_001))

start = time.time()
discounted_loop = [p * 0.95 for p in prices]
loop_time = time.time() - start
print(f"Loop version: {loop_time:.4f} seconds")

prices_np = np.arange(1, 1_000_001)

start = time.time()
discounted_np = prices_np * 0.95
np_time = time.time() - start
print(f"Numpy version: {np_time:.4f} seconds")

print(f"Numpy was about {loop_time / np_time:.0f}x faster")

Loop version: 0.1549 seconds
Numpy version: 0.0081 seconds
Numpy was about 19x faster


In [15]:
a = np.array([10, 20, 30, 40])
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
seq = np.arange(0, 10, 2)
lin = np.linspace(0, 1, 5)

print("a:", a)
print("zeros:\n", zeros)
print("ones:\n", ones)
print("seq:\n", seq)
print("lin:\n", lin)

a: [10 20 30 40]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
seq:
 [0 2 4 6 8]
lin:
 [0.   0.25 0.5  0.75 1.  ]


Array attributes

In [4]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print("shape:", matrix.shape)
print("ndim:", matrix.ndim)
print("size:", matrix.size)
print("dtype:", matrix.dtype)

shape: (2, 3)
ndim: 2
size: 6
dtype: int32


Reshaping

In [5]:
flat = np.arange(12)
print("flat:", flat)
reshaped = flat.reshape(3, 4)
print("reshaped (3x4):\n", reshaped)
back_to_flat = reshaped.flatten()
print("flattened again:", back_to_flat)

flat: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened again: [ 0  1  2  3  4  5  6  7  8  9 10 11]


Indexing, slicing & boolean masking

In [7]:
sales = np.array([120, 85, 200, 0, 60, 300, 45])

print("first element:", sales[0])
print("last element:", sales[-1])
print("first 3:", sales[:3])
print("every other:", sales[::2])

mask = sales > 100
print("mask:", mask)
print("sales above 100:", sales[mask])
print("days with zero sales:", sales[sales <= 150])

first element: 120
last element: 45
first 3: [120  85 200]
every other: [120 200  60  45]
mask: [ True False  True False False  True False]
sales above 100: [120 200 300]
days with zero sales: [120  85   0  60  45]


Vectorization & Broadcasting

In [8]:
units_sold = np.array([10, 25, 8, 40])
unit_price = np.array([15000, 22000, 9500, 30000]) # KRW
revenue = units_sold * unit_price
print("revenue per product:", revenue)
print("total revenue:", revenue.sum())

revenue per product: [ 150000  550000   76000 1200000]
total revenue: 1976000


Broadcasting

In [9]:
# Monthly sales for 3 stores (rows) across 4 products (columns)
store_sales = np.array([
[100, 200, 150, 300],
[120, 180, 170, 250],
[90, 210, 160, 280]
])
# Apply a single discount rate to every value
discount = 0.10
print("after 10% discount:\n", store_sales * (1 - discount))
# Add a per-product bonus (shape (4,)) to every row — broadcasting in action
product_bonus = np.array([5, 0, 10, 2])
print("\nwith per-product bonus:\n", store_sales + product_bonus)

after 10% discount:
 [[ 90. 180. 135. 270.]
 [108. 162. 153. 225.]
 [ 81. 189. 144. 252.]]

with per-product bonus:
 [[105 200 160 302]
 [125 180 180 252]
 [ 95 210 170 282]]


In [10]:
print("total per store (axis=1, across columns):", store_sales.sum(axis=1))
print("total per product (axis=0, down rows):", store_sales.sum(axis=0))
print("overall mean:", store_sales.mean())
print("best-selling product per store:", store_sales.argmax(axis=1))

total per store (axis=1, across columns): [750 720 740]
total per product (axis=0, down rows): [310 590 480 830]
overall mean: 184.16666666666666
best-selling product per store: [3 3 3]


In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A:\n", A)

A:
 [[1 2]
 [3 4]]


In [12]:
# Rows = portfolios, columns = shares held in 4 assets
holdings = np.array([
[10, 5, 0, 20],
[0, 15, 10, 5],
[8, 8, 8, 8]
])
# Current price per share for each of the 4 assets
prices = np.array([50000, 120000, 75000, 30000])
portfolio_value = holdings @ prices
print("value of each portfolio (KRW):", portfolio_value)

value of each portfolio (KRW): [1700000 2700000 2200000]


In [13]:
I = np.eye(3)
print("identity matrix:\n", I)
M = np.array([[2, 1], [1, 3]])
M_inv = np.linalg.inv(M)
print("\nM inverse:\n", M_inv)
print("M @ M_inv (should be ~identity):\n", np.round(M @ M_inv, 2))
# Solve the system: 2x + y = 5 ; x + 3y = 10
coeffs = np.array([[2, 1], [1, 3]])
results = np.array([5, 10])
solution = np.linalg.solve(coeffs, results)
print("\nsolution [x, y]:", solution)

identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

M inverse:
 [[ 0.6 -0.2]
 [-0.2  0.4]]
M @ M_inv (should be ~identity):
 [[ 1.  0.]
 [-0.  1.]]

solution [x, y]: [1. 3.]


In [14]:
np.random.seed(42)
uniform_samples = np.random.rand(5) # uniform [0, 1)
integers = np.random.randint(1, 7, size=10) # simulate 10 dice rolls
normal_samples = np.random.normal(loc=170, scale=8, size=5) # e.g., heights in cm
print("uniform:", uniform_samples)
print("dice rolls:", integers)
print("normal samples:", normal_samples)

uniform: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
dice rolls: [3 3 3 5 4 3 6 5 2 4]
normal samples: [170.17777461 166.57765669 165.74546072 169.06019599 171.77663121]


In [15]:
np.random.seed(42)
rolls = np.random.randint(1, 7, size=100_000)
prob_six = (rolls == 6).mean()
print(f"P(rolling a 6): {prob_six:.4f} (theoretical: {1/6:.4f})")
avg_roll = rolls.mean()
print(f"average roll: {avg_roll:.3f} (theoretical: 3.5)")

P(rolling a 6): 0.1663 (theoretical: 0.1667)
average roll: 3.503 (theoretical: 3.5)


In [16]:
np.random.seed(1)
days = 30
daily_returns = np.random.normal(loc=0.001, scale=0.02, size=days) # ~0.1% avg daily return
price = 10000 * np.cumprod(1 + daily_returns) # starting price = 10,000
print("simulated closing prices:\n", np.round(price, 0))
print("\nfinal price after", days, "days:", round(price[-1], 0))

simulated closing prices:
 [10335. 10219. 10121.  9914. 10095.  9641.  9987.  9845.  9918.  9878.
 10177.  9768.  9714.  9649.  9878.  9671.  9647.  9487.  9505.  9625.
  9423.  9648.  9831.  9940. 10129. 10001.  9986.  9809.  9766.  9880.]

final price after 30 days: 9880.0
